filebeat.inputs:
- type: container
  paths:
    - '/var/lib/docker/containers/*/*.log'
  json.keys_under_root: true
  json.add_error_key: true
  json.message_key: message
  json.overwrite_keys: true
  tags: ["fastapi"]
  processors:
    - add_docker_metadata:
        host: "unix:///var/run/docker.sock"
    - add_fields:
        target: ''
        fields:
          service: fastapi

processors:
- add_host_metadata: ~
- add_docker_metadata:
    host: "unix:///var/run/docker.sock"

output.elasticsearch:
  hosts: ["elasticsearch:9200"]
  indices:
    - index: "fastapi-logs-%{+yyyy.MM.dd}"
      when.contains:
        tags: "fastapi"

setup.ilm.enabled: false
setup.template.enabled: true
logging.json: true